package io.github.awsopstoolkit.configuration;

import static org.junit.jupiter.api.Assertions.*;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import org.junit.jupiter.api.Test;

class ConfigurationMetadataTest {
    @Test
    void generatedMetadataContainsTypedOperationalPropertiesAndSafeDefaults() throws Exception {
        try (InputStream in =
                getClass()
                        .getClassLoader()
                        .getResourceAsStream("META-INF/spring-configuration-metadata.json")) {
            assertNotNull(in, "Spring configuration metadata must be generated by the build");
            String metadata = new String(in.readAllBytes(), StandardCharsets.UTF_8);

            assertTrue(metadata.contains("\"name\": \"toolkit.operations.shutdown-timeout\""));
            assertTrue(metadata.contains("\"name\": \"toolkit.operations.dry-run-sample-size\""));
            assertTrue(
                    metadata.contains(
                            "\"name\": \"toolkit.operations.estimated-bytes-per-record\""));
            assertTrue(metadata.contains("\"name\": \"toolkit.dynamodb.tables\""));
            assertTrue(metadata.contains("\"name\": \"toolkit.journal.busy-timeout\""));
            assertTrue(metadata.contains("\"name\": \"toolkit.report.flush-every-records\""));
            assertTrue(metadata.contains("\"name\": \"toolkit.s3.multipart-part-size\""));
            assertTrue(metadata.contains("\"name\": \"toolkit.sqs.receive-wait-time\""));

            assertPropertyDefault(metadata, "toolkit.core.max-concurrent-operations", "2");
            assertPropertyDefault(metadata, "toolkit.core.page-size", "100");
            assertPropertyDefault(metadata, "toolkit.aws.enabled", "false");
            assertPropertyDefault(metadata, "toolkit.operations.writes", "false");
        }
    }

    private static void assertPropertyDefault(
            String metadata, String property, String defaultValue) {
        int start = metadata.indexOf("\"name\": \"" + property + "\"");
        assertTrue(start >= 0, () -> "Missing property metadata: " + property);
        int next = metadata.indexOf("\"name\":", start + property.length() + 10);
        String block = next < 0 ? metadata.substring(start) : metadata.substring(start, next);
        assertTrue(
                block.contains("\"defaultValue\": " + defaultValue)
                        || block.contains("\"defaultValue\": \"" + defaultValue + "\""),
                () -> "Unexpected default metadata for " + property + ": " + block);
    }
}
